language: node_js

install:
- npm install
- npm install --prefix ./packages/spark-core

before_script:
- npm run test --prefix ./packages/spark-core

after_success:
- pecl install imagick
- npm install -g phantomjs
- gem install wraith && npm run visual-regression

cache:
  directories:
    - node_modules
    - packages/spark-core/node_modules
